#!/bin/sh
#/usr/bin/curl -X POST http://lfmdev.cogknit.com:8088/jenkins/git/notifyCommit?url=git@github.com:vijethas/repos.test.com.git
#/usr/bin/curl -X POST http://lfmdev.cogknit.com:8088/job/Test//build?token=gittest
/usr/bin/wget \
  --header "Content-Type:text/plain;charset=UTF-8" \
  --output-document "-" \
  --timeout=2 \
  http://lfmdev.cogknit.com:8088/jenkins/git/notifyCommit?url=git@github.com:vijethas/repos.test.com.git
echo "Build Triggered"
